//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleManager.Web.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public int Type { get; set; }
        public int CustomerId { get; set; }
        public int SuplierId { get; set; }
        public bool IsPayment { get; set; }
        public decimal Amount { get; set; }
        public decimal Payment { get; set; }
        public decimal PayBack { get; set; }
        public string BillNumber { get; set; }
    }
}
